project:
  type: website
  output-dir: docs

website:
  title: "Maeve's Crocheting"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - current_projects.qmd
      - future_projects.qmd
      - past-projects.qmd

format:
  html:
    theme: Darkly
    css: styles.css
    toc: true
    page-layout: full



